# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master", "feat/**", "renovate/**", "dependabot/**" ]
  pull_request:
    branches: [ "master", "feat/**", "renovate/**", "dependabot/**" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js $(cat .node-version)
      uses: actions/setup-node@v3
      with:
        node-version: $(cat .node-version)
        cache: 'npm'
    - run: yarn
    - run: yarn codegen
      env:
        API_TOKEN: ${{ secrets.NEXT_PUBLIC_API_TOKEN }}
    - run: yarn build
      env:
        API_TOKEN: ${{ secrets.NEXT_PUBLIC_API_TOKEN }}
    - run:
        yarn confirm
    - run:
        yarn test
      env:
        API_TOKEN: ${{ secrets.NEXT_PUBLIC_API_TOKEN }}
